version : '3'
services:
 jenkins:
  image: jenkins/jenkins:lts
  ports:
    - "8080:8080"

 
 gitlab:
  image: gitlab/gitlab-ce
  ports:
    - "8090:8090"
  volumes:
    - "jenkinsdata:/var/jenkins_home"
volumes:
  jenkinsdata: